### ISSUE TITLE
Consuming Rx operators: missing JSPM package?

### ISSUE THREAD

**Issue by Myrmex** [dsebastien/modernWebDevGenerator#70]
Hi, I'm playing with your template which looks great, especially for an Angular2 beginner. I started using it, but consuming Rx does not seem a trivial task: as soon as I need some Rx operator I find myself in trouble in importing them. This seems a common issue for many configurations, but I'm a newbie in the world of JS packages. 

If I do something like `import {Observable} from "rxjs/Observable"` this works, but if I try with something like `import "rxjs/add/operator/map"` (see https://github.com/angular/angular/issues/5632#issuecomment-167026172), I get 404 errors like "http://localhost:3000/jspm_packages/npm/rxjs@5.0.0-beta.0/add/operator/subscribe.js 404 (Not Found)" (the specified file is effectively not present in that directory nor under add/operator in the same folder).

I tried the following installs, without luck:

```
jspm install rx (http://caughtexceptions.blogspot.it/2015/09/rxjs-with-jspm-and-typescript.html)
```

and

```
jspm install npm:@reactivex/rxjs
```

Could you give a hint or point me to some learning resource about this? It seems configuring a development environment is much harder than learning Angular2 itself...:)

**Comment by dsebastien** [comment]
Hi @Myrmex! You're right, it's far from straightforward to get up and running :)

I remember having trouble with that at some point. The thing is that for now, JSPM integration with TypeScript isn't great which is why I duplicated some dependencies in the package.json file. If you look at it you'll see that (by default with my project generator), you have duplicate dependencies for Angular 2, RxJS, ... This allows the TypeScript compiler to locate the modules, etc. I'll leave that like that until TypeScript provides a way to alias things.

Normally with a newly generated project, you shouldn't have to add RxJS yourself (it's in by default). Note that the import you mentioned (@reactivex/rxjs) is the "old" one. Angular 2 now uses RxJS 5.0.0-alpha which has changed name and is now simply called `rxjs`.

If you have the rxjs module installed, then you'll see that the add/operator/map exists in the package's folder structure :)

```
import {Observable, Subject} from "rxjs";
import "rxjs/add/operator/map";
```
