### ISSUE TITLE
question about jasmine

### ISSUE THREAD

**Issue by skywalker5727** [dsebastien/modernWebDevGenerator#85]
I am a tester and am trying to figure out how to set up karma/jasmine - I am new to very many things in the Angular2 world and am just learning.  I see your typings.json has jasmine under dependencies.  My instincts were to put it under ambientDevDependencies.  Why did you choose dependencies?

**Comment by dsebastien** [comment]
Hey Luke,

I just used typings to install those and that's it, thus it has found a version of the typings I asked for and I didn't really think beyond that. 

TypeScript uses tsconfig.json as basis to determine what to include or not and thus the tsconfig.json is the only thing that influence which typing files (*.d.ts files) will be taken into account while compiling, hence whether the jasmine typings are under dependencies or ambientDevDependencies won't change much in practice.

What will make a difference is if the typing files are actually different, in which case your code might match what one typing file describes and maybe not what another typing file describe :)

Thus in practice as long as good typings are available, the compiler will be able to help more.

Note that there's currently an issue with the way I reference the typings in the example unit test. I was forced to use a /// reference because of an issue with gulp-typescript, which does not behave exactly like the typescript compiler (tsc) does.

**Comment by skywalker5727** [comment]
Thank you for taking the time to reply.  I'm slowly understanding how all
these files hang together.  I did a little playing around/learning with
Jasmine and Karma using plain JavaScript, but the team I am currently
working on will be trying a project in Angular2, so I'm figuring out how to
incorporate TypeScript.  I've learned I need to look at very recent posts
when searching the web :).   I found your project in your reply in Stack
Overflow by an irate hockey player a few days ago.

Luke/Lucy

On Thu, Feb 18, 2016 at 11:47 AM, Sebastien Dubois <notifications@github.com

**Comment by dsebastien** [comment]
Well it ain't very straightforward, especially with the combination of SystemJS/JSPM and all the tooling (Karma, Protractor, ...).

If you look at the issues of the project, you'll see that around testing, this project remains pretty weak (e.g., it doesn't include e2e testing nor test coverage, etc).

I wouldn't personally recommend using this build as is at this point. Or you'd better be committed to contribute :p

I also think that currently, SystemJS/JSPM have too many integration issues with TypeScript (e.g., look at the dependencies I had to duplicate to make it all work); rather, I think that webpack is the best option for build/bundling/loading around for now.

The combination of gulp and TypeScript is also not great (cfr my previous comment).

Thus to summarize, one nice evolution of my [modernWebDevBuild](https://github.com/dsebastien/modernWebDevBuild) project could be to support webpack :)

Hope this helps Lucy :)
