### ISSUE TITLE
Issue on gulp serve-dist & gulp

### ISSUE THREAD

**Issue by superdave7380** [dsebastien/modernWebDevGenerator#94]
Hi there,

I apologize for writing you here -- feel free to delete this issue -- but your email appears to be full (_550 sorry, user over quota..._) so I have no choice!

I'm _really_ hoping you can help me with an issue I'm having with your Yeoman generator. 

For the most part, it works great. I'm able to run `npm start` which loads the dev server. Everything works as expected. Awesome.

The problems happen when I try to either run `gulp serve-dist` or simply `gulp`to create the dist package.

On `gulp serve-dist`, it can't find my component files.

**`> GET http://localhost:3000/app/modules/window/window.template.html 404 (Not Found)
EXCEPTION: Failed to load app/modules/window/window.template.html`**
(_window_ is one of my components)

And on `gulp`, when I load up the index.html, it appears to not be able to find anything!

**`> GET file:///C:/Users/David/Documents/dev/web/proj/app/styles/vendor.css net::ERR_FILE_NOT_FOUND`**
(and that error repeats for the remainder of the files referenced in index.html)

Am I doing something wrong?? (I'm probably doing something wrong...)

Again, everything works perfectly through the dev server (`npm start`).

My project is stored in a Bitbucket repository. I would be happy to share it with you if think that might help and you can spare a minute or two....

Thanks in advance for any help you may be able to provide. I really appreciate it.

David
superdave7380 at gmail.com

**Comment by dsebastien** [comment]
Hey there.
I might be able to help if I can see your code indeed, but that's up to you :)

Which version of the build (https://github.com/dsebastien/modernWebDevBuild) are you using? I remember that I fixed some issues with the production css bundles because there were path issues so this could be related..

Take a look at the upgrade guide: https://github.com/dsebastien/modernWebDevBuild/blob/master/CHANGELOG.MD and see if you need to change things in your project to be able to use the latest release.

**Comment by superdave7380** [comment]
I'm on the very latest release. 0.5.2 of the generator. I had even started over completely to be sure.
I've provided you - seb@dsebastien.net - with read access to the repo, https://bitbucket.org/superdave7380/soapbox/ Let me know if you can't access.
And thanks again for your speedy reply.

**Comment by dsebastien** [comment]
Okay, I'll take a look.
I just validated that a freshly generated project works correctly whether using the dev or prod version.
But indeed the freshly generated projects are pretty raw ;-)

**Comment by superdave7380** [comment]
Thanks very much! (Chances are more likely than not that I don't know what the heck I'm doing...)

**Comment by dsebastien** [comment]
The first thing I notice is that there's a timing issue of sorts. When the server starts and the browser opens, bundle.min.css & bundle.min.js files are not there yet (or not served yet), leading to the two 404 errors. Refreshing shows that those are then found, thus there could already be an issue with the chaining of the gulp tasks.

At first sight, I don't see where the issue is but it's not the first time I've seen this...
The culprit is either there: https://github.com/dsebastien/modernWebDevBuild/blob/master/src/gulp/tasks/default.js or there: https://github.com/dsebastien/modernWebDevBuild/blob/master/src/gulp/tasks/serve-dist.js

Maybe the BrowserSync reload call in there is causing he issue, honestly I have no idea (I don't remember why that one's there ^^):
https://github.com/dsebastien/modernWebDevBuild/blob/master/src/gulp/tasks/check-js-quality.js#L25

**Comment by superdave7380** [comment]
Okay. That's not good. But on the positive side, it might not be something I did, I'm not delusional and may have found a genuine bug.

**Comment by dsebastien** [comment]
If we ignore that issue for now (I'll create a specific issue for the build), for the remaining errors, it's just a problem with the relative paths.

The build documentation should be clearer, but one thing to know is that when you run the dev server, the content that is served is actually an overlay of:
- the project root folder (i.e., where node_modules & jspm_packages are)
- the contents of the app folder

This means that when the dev web server is started, node_modules and jspm_packages (and all the rest incidentally) are available at the same level as the other resources.

I did this because I wanted to avoid having to copy files from jspm_packages/node_modules around.

The negative side effect is that well, you can get some paths working in dev that won't work in prod :)

What this means is that for template URLs, you should not specify the app folder. You have to provide a relative path from the app folder itself, thus for example `templateUrl: "modules/header/header.template.html",` instead of `templateUrl: "app/modules/header/header.template.html",`

**Comment by superdave7380** [comment]
That makes perfect sense. Don't know why I didn't spot that before. Thanks very much.

**Comment by dsebastien** [comment]
For the styleUrls though I don't really have a solution. What you're doing is indeed correct (I like the idea of isolating styles per component), but the way the build currently works doesn't really support that.

Basically for styles, the build goes from main.scss and vendor.scss and creates a full bundle for each containing everything. Thus what you define in modules/footer/footer.scss just ends up in bundle.min.css.

If you've got ideas about this, don't hesitate (honestly for now I don't ^^).

**Comment by superdave7380** [comment]
Gotcha. But what about the issue where the vendor or main css files (or others) are not being found when I simply load up dist/index.html (after plain gulp)? (unless you answered that and I missed it)

**Comment by dsebastien** [comment]
In dev the behavior is indeed different because there are no bundles involved.

An idea for supporting your use case could maybe be to do the following for production:
- load all partial SASS files (i.e., starting with _) + main.scss
  - transpile those and bundle them in bundle.min.css
- perform a second pass where all non-partial SASS files with the exception of main.scss
  - transpile those in place (just like in dev)

You'd thus end up with one global css bundle containing everything that you imported there and one css file for each case where you want/need isolation (e.g., your sass per component).

Although I'm not sure at all this would be efficient in production (ignoring HTTP/2 as that was never considered with my build)

**Comment by superdave7380** [comment]
Sorry, I don't think I was being clear.
1. I renamed my templateUrls to remove the app reference as you indicated.
2. I also remove the styleUrls and instead added appropriate import statements to your main.scss
   **RESULT**: _gulp serve-dist_ WORKS! (after refreshing because browser-sync loads too fast) **AWESOME**!

But on _gulp_, then simply opening index.html in the browser, I still get the issue where none of the files referenced in the index are found:
- `file:///C:/Users/David/Documents/dev/web/soapbox/app/styles/vendor.css Failed to load resource: net::ERR_FILE_NOT_FOUND`
- and so on.. es6-shim.js... system.js.. etc etc..

Clearly some reference error.
And this is the bigger issue because until I resolve this issue, I can't host the project anywhere.

I'm sorry to keep bothering you with this.. I truly appreciate your help.
- repo updated

**Comment by dsebastien** [comment]
Well if this is open source then the goal is that people use it at some point ;-)

**Comment by superdave7380** [comment]
Ya, but it doesn't work! If I can't load the index.html without all the reference errors.... And you say it works fine off a clean project? So I must be doing something wrong... but where?!

**Comment by superdave7380** [comment]
And it's not open source.. Only to you...... for now.......... ;)

**Comment by dsebastien** [comment]
Honestly you should simply not try and open the page like that.
If you want to make a useful test, then you can try with a web server like http-server, superstatic, or whichever else you like:

```
npm install -g superstatic
superstatic
```

Once started, just look at the port number and open http://localhost:<port> in your browser. That'll work better.

If you look at the 404 errors that you get when you open it as file:///..., you'll see that all relative paths end up at the root of your file system, which is clearly not going to work.

Just start up an actual web server :)

**Comment by superdave7380** [comment]
Uhuh.... (this is me just being suuuuuper unknowledgeable). So you're saying if just upload the project to my webhost, where I've currently got my other projects, it'll magically work? No kidding!

**Comment by dsebastien** [comment]
Just try, you'll see ;-)

**Comment by superdave7380** [comment]
Holy shit. It works. That's awesome. I can't thank you enough for you help. Seriously. Have a fantastic day.

**Comment by dsebastien** [comment]
Glad I could help ;-)

FYI I just published a new version of the build that fixes the issue on first display:
- https://github.com/dsebastien/modernWebDevBuild/releases/tag/0.5.1
- https://www.npmjs.com/package/modern-web-dev-build

Have a nice day!

**Comment by superdave7380** [comment]
Damn, I had no intention of having a follow-up question...
If I use the generator, I should just wait for that one to be updated and then scaffold over the project again, right?

**Comment by dsebastien** [comment]
I have no idea if that works, never tested :)
I created the generated but I'm not too familiar with Yeoman thus either that's how Yeoman works and that's awesome, or I need to implement something in the generator myself and I don't know what/how.

In this case you can simply change the dependency towards modern-web-dev-build to 0.5.1.

**Comment by superdave7380** [comment]
Yep, that's how the generators work as far as I've read. It gives you the diff of each file with changes and asks what you want to do. Aaaaaaaaanyways, thanks again. Really. (REALLY). Have a great day.
